In [1]:
%matplotlib inline

In [2]:
!which python

/Applications/anaconda/envs/ulab/bin/python



What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [3]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.Tensor(5, 3)
print(x) # What does this print out? Why?


 0.0000e+00 -8.5899e+09 -2.0445e+34
 4.6577e-10  8.4078e-45  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00 -8.5899e+09  0.0000e+00
[torch.FloatTensor of size 5x3]



In [5]:
x = torch.zeros(5, 3) # Usually better to do this instead of torch.Tensor
print(x)


 0  0  0
 0  0  0
 0  0  0
 0  0  0
 0  0  0
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix:



In [6]:
x = torch.rand(5, 3)
print(x)


 0.0239  0.8092  0.1620
 0.9791  0.5046  0.5714
 0.7770  0.8807  0.1416
 0.0946  0.5554  0.0097
 0.4447  0.9549  0.3836
[torch.FloatTensor of size 5x3]



Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

#### Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)


 0.2841  1.5624  0.4243
 1.6490  0.9046  1.0559
 0.8238  1.2282  0.5573
 0.7628  0.9450  0.4673
 0.7698  1.3013  0.7538
[torch.FloatTensor of size 5x3]



#### Addition: syntax 2



In [9]:
print(torch.add(x, y))


 0.2841  1.5624  0.4243
 1.6490  0.9046  1.0559
 0.8238  1.2282  0.5573
 0.7628  0.9450  0.4673
 0.7698  1.3013  0.7538
[torch.FloatTensor of size 5x3]



#### Addition: providing an output tensor as argument



In [10]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.2841  1.5624  0.4243
 1.6490  0.9046  1.0559
 0.8238  1.2282  0.5573
 0.7628  0.9450  0.4673
 0.7698  1.3013  0.7538
[torch.FloatTensor of size 5x3]



#### Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)


 0.2841  1.5624  0.4243
 1.6490  0.9046  1.0559
 0.8238  1.2282  0.5573
 0.7628  0.9450  0.4673
 0.7698  1.3013  0.7538
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])


 0.8092
 0.5046
 0.8807
 0.5554
 0.9549
[torch.FloatTensor of size 5]



Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array



In [14]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [16]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



## Exercises
Most of these exercises can be completed by using some Pytorch method. Take a look at the Pytorch documentation: http://pytorch.org/docs/0.3.1/torch.html. These exercises are mainly for you to get familiar with variance Pytorch methods.

#### 1) Write a method that finds the maximum of each row of a matrix

In [26]:
def q1(X):
    return torch.max(X,1)[0]

X = torch.Tensor([[1,2,1], [1,2,3], [3,2,1]])
actual = q1(X)

expected = torch.Tensor([2,3,3])
if torch.equal(actual, expected):
    print('Passed')
else:
    print('Actual: %s, Expected: %s' % (actual, expected))

Passed


#### 2) Write a method that finds the index of the maximum element of each row of a matrix

In [27]:
def q2(X):
    return torch.max(X,1)[1]

X = torch.Tensor([[1,2,1], [1,2,3], [3,2,1]])
actual = q2(X)

expected = torch.LongTensor([1,2,0])
if torch.equal(actual, expected):
    print('Passed')
else:
    print('Actual: %s, Expected: %s' % (actual, expected))

Passed


#### 3) Write a method that flattens a Tensor into a 1-dimensional vector. See the methods in torch.Tensor http://pytorch.org/docs/master/tensors.html

In [36]:
def q3(X):
    return X.view(X.size()[0] * X.size()[1])

X = torch.rand(10, 5)
actual = q3(X)
if len(actual.size()) == 1 and actual.size(0) == actual.numel():
    print('Passed')
else:
    print('Failed')

Passed


#### 4) Generate an $n\times n$ identity matrix

In [38]:
def q4(n):
    return torch.eye(3)

actual = q4(3)
expected = torch.Tensor([[1,0,0], [0,1,0], [0,0,1]])
if torch.equal(actual, expected):
    print('Passed')
else:
    print('Actual: %s, Expected: %s' % (actual, expected))

Passed


#### 5) Given a tensor, remove all dimensions of size 1. For example, if the size of tensor $X$ is $1 \times 10 \times 5 \times 1 \times 2$, the method should return a tensor with the same elements as $X$, but with size $10 \times 5 \times 2$

In [49]:
def q5(X):
    return torch.squeeze(X)

X = torch.rand(1, 1, 10, 1, 4)
actual = q5(X).size()
expected = torch.zeros(10, 4).size()
if actual == expected:
    print('Passed')
else:
    print('Actual Size: %s, Expected Size: %s' % (actual, expected))

Passed
